VuHoangLam/VuHoangLam/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VuHoangLam.Models
{
    public class GioHang
    {
        DbRubikStore db = new DbRubikStore();
        public int Id { get; set; }
        //[Display(Name = "Tên")]
        public string Ten { get; set; }

        //[Display(Name = "Ảnh bìa")]
        public string Hinh { get; set; }
        //[Display(Name = "Giá bán")]
        public Double Gia { get; set; }
        //[Display(Name = "Số lượng")]
        public int SoLuong { get; set; }
        //[Display(Name = "Thành tiền")]
        public Double ThanhTien
        {
            get { return SoLuong * Gia; }
        }

        public GioHang(int id)
        {
            this.Id = id;
            Rubik rubik = db.Rubiks.Single(s => s.id == id);
            Ten = rubik.ten;
            Hinh = rubik.hinh;
            Gia = double.Parse(rubik.gia.ToString());
            SoLuong = 1;
        }
    }
}

VuHoangLam/VuHoangLam/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VuHoangLam.Models;

namespace VuHoangLam.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        DbRubikStore db = new DbRubikStore();
        public List<GioHang> LayGioHang()
        {
            List<GioHang> listGioHang = Session["GioHang"] as List<GioHang>;
            if(listGioHang == null)
            {
                listGioHang = new List<GioHang>();
                Session["GioHang"] = listGioHang;
            }
            return listGioHang;
        }

        public ActionResult ThemGioHang(int id, string strUrl)
        {
            List<GioHang> listGioHang = LayGioHang();
            GioHang gh = listGioHang.Find(n => n.Id == id);
            if(gh == null)
            {
                gh = new GioHang(id);
                listGioHang.Add(gh);
                return Redirect(strUrl);
            }
            else
            {
                gh.SoLuong++;
                return Redirect(strUrl);
            }
        }

        private int TongSoLuong()
        {
            int result = 0;
            List<GioHang> listGioHang = Session["GioHang"] as List<GioHang>;
            if (listGioHang != null)
            {
                result = listGioHang.Sum(n => n.SoLuong);
            }
            return result;
        }

        private int TongSoLuongSanPham()
        {
            int result = 0;
            List<GioHang> listGioHang = Session["GioHang"] as List<GioHang>;
            if (listGioHang != null)
            {
                result = listGioHang.Count;
            }
            return result;
        }

        private double TongTien()
        {
            double result = 0;
            List<GioHang> listGioHang = Session["GioHang"] as List<GioHang>;
            if (listGioHang != null)
            {
                result = listGioHang.Sum(n => n.ThanhTien);
            }
            return result;
        }

        public ActionResult GioHang()
        {
            List<GioHang> listGioHang = LayGioHang();
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return View(listGioHang);
        }

        public ActionResult GioHangPartial()
        {
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return PartialView();
        }

        public ActionResult XoaGioHang(int id)
        {
            List<GioHang> listGioHang = LayGioHang();
            GioHang gh = listGioHang.SingleOrDefault(n => n.Id == id);
            if (gh == null)
            {
                listGioHang.RemoveAll(n => n.Id == id);
                return RedirectToAction("GioHang");
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult CapNhatGioHang(int id, FormCollection collection)
        {
            List<GioHang> listGioHang = LayGioHang();
            GioHang gh = listGioHang.SingleOrDefault(n => n.Id == id);
            if(gh == null)
            {
                gh.SoLuong = int.Parse(collection["txtSoLuong"].ToString());
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult ChiTietGioHang(int? id)
        {
            if(id == null)
            {
                return HttpNotFound();
            }
            List<GioHang> listGioHang = LayGioHang();
            GioHang gh = listGioHang.Find(n => n.Id == id);
            if( gh == null)
            {
                return HttpNotFound();
            }
            return View(gh);
        }
    }
}

VuHoangLam/VuHoangLam/Controllers/RubikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VuHoangLam.Models;

namespace VuHoangLam.Controllers
{
    public class RubikController : Controller
    {
        // GET: Rubik
        DbRubikStore db = new DbRubikStore();
        public ActionResult Index()
        {
            var all_Rubik = db.Rubiks.ToList();
            return View(all_Rubik);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Rubik rubik = db.Rubiks.Find(id);
            if (rubik == null)
            {
                return HttpNotFound();
            }
            return View(rubik);
        }
    }
}

VuHoangLam/VuHoangLam/Views/GioHang/ChiTietGioHang.cshtml
@model VuHoangLam.Models.GioHang

@{
    ViewBag.Title = "ChiTietGioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ChiTietGioHang</h2>

<div>
    <h4>GioHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>

        <dd>
            <img src="/@Html.DisplayFor(model => model.Hinh)" width="50px" alt="" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThanhTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThanhTien)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VuHoangLam/VuHoangLam/Views/GioHang/GioHang.cshtml
@model IEnumerable<VuHoangLam.Models.GioHang>

@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Giỏ Hàng</h2>

<table class="table">
    <tr>
        <th>
            Tên
        </th>
        <th>
            Hình ảnh
        </th>
        <th>
            Giá bán
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Thành tiền
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                <img src="@item.Hinh" width="50px" alt="" />
            </td>
            @using (Html.BeginForm("CapNhatGioHang", "GioHang", new { @id = item.Id }))
            {
                <td> @String.Format("{0:0,0}", item.Gia) VNĐ </td>
                <td> <input type="number" min="1" name="txtSoLuong" value="@item.SoLuong" /></td>
                <td> @Html.DisplayFor(modelItem => item.ThanhTien) </td>
                <td>
                    <a href="@Url.Action("Details", "Rubik", new { id = item.Id })">Chi tiết</a> | @Html.ActionLink("Xóa", "XoaGioHang", new { @id = item.Id })
                </td>
                <td>
                    <input type="submit" value="Cập nhật" class="btn btn-success" />
                </td>
            }
        </tr>
     }
     <tr style="font-weight: bold; text-align: left; color: red">
         <td colspan="2"> Số loại rubik: @ViewBag.Tongsoluongsanpham </td>
         <td colspan="2"> Số lượng rubik: @ViewBag.Tongsoluong </td>
         <td colspan="4"> Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien) VNĐ
     </td>
     </tr>
     
     <tr style="font-weight: bold; color: blue; text-align: right">
         <td colspan="5">
             @Html.ActionLink("Xóa giỏ hàng", "XoaTatCaGioHang")
         </td>
     </tr>
     <tr style="font-weight: bold; color: yellow; text-align: right">
         <td colspan="5">
             @Html.ActionLink("Đặt hàng", "DatHang", "GioHang")
         </td>
     </tr>
</table>

VuHoangLam/VuHoangLam/Views/GioHang/GioHangPartial.cshtml
<a class="getstarted scrollto active" href="@Url.Action("GioHang", "GioHang")" style="font-weight:bold; text-decoration:none">
    Giỏ hàng (@ViewBag.Tongsoluongsanpham)
</a>